<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-QT8RIA1" name="com.test.ExceptionTimeOutTest" tests="2" failures="0" timestamp="2020-04-01T10:01:15 IST" time="5.029" errors="1">
  <testcase name="timeoutTest" time="5.012" classname="com.test.ExceptionTimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.test.ExceptionTimeOutTest.timeoutTest() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.ExceptionTimeOutTest.timeoutTest() didn't finish within the time-out 5000
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:715)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1014)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- timeoutTest -->
  <testcase name="exceptionTest" time="0.017" classname="com.test.ExceptionTimeOutTest"/>
</testsuite> <!-- com.test.ExceptionTimeOutTest -->
